const businessTypes=[
    { label: 'Shop', id: '1' },
    { label: 'Site', id: '2' },
    { label: 'Service Provider', id: '3' },
    { label: 'Consultant', id: '4' },
    { label: 'Manufacturer', id: '5' },
    { label: 'Distributor', id: '6' },
    { label: 'Retailer', id: '7' },
    { label: 'Supplier', id: '8' },
    { label: 'Agency', id: '9' },
    { label: 'Investment Firm', id: '10' },
    { label: 'Law Firm', id: '11' },
    { label: 'Startup', id: '12' },
    { label: 'Nonprofit', id: '13' },
    { label: 'Consortium', id: '14' },
    { label: 'Hospital', id: '15' },
    { label: 'University', id: '16' },
    { label: 'Research Institute', id: '17' },
    { label: 'Government Agency', id: '18' },
    { label: 'Insurance Provider', id: '19' },
    { label: 'Financial Institution', id: '20' },
    { label: 'Real Estate Company', id: '21' },
    { label: 'Advertising Agency', id: '22' },
    { label: 'Consulting Firm', id: '23' },
    { label: 'Technology Company', id: '24' },
    { label: 'Recruiting Agency', id: '25' },
    { label: 'Management Company', id: '26' },
    { label: 'Logistics Provider', id: '27' },
    { label: 'Healthcare Provider', id: '28' },
    { label: 'IT Solutions Company', id: '29' },
    { label: 'Software Development Company', id: '30' },
    { label: 'Public Relations Agency', id: '31' },
    { label: 'Marketing Agency', id: '32' },
    { label: 'Data Analysis Company', id: '33' },
    { label: 'Graphic Design Company', id: '34' },
    { label: 'Web Design Company', id: '35' },
    { label: 'Security Company', id: '36' },
    { label: 'Social Media Agency', id: '37' },
    { label: 'Data Science Company', id: '38' },
    { label: 'AI & Machine Learning Company', id: '39' },
    { label: 'Business Analytics Company', id: '40' },
    { label: 'Product Management Company', id: '41' },
    { label: 'Training Company', id: '42' },
    { label: 'Manufacturing Company', id: '43' },
    { label: 'Construction Company', id: '44' },
    { label: 'Transportation Company', id: '45' },
    { label: 'Warehousing Company', id: '46' },
    { label: 'Retail Company', id: '47' },
    { label: 'Project Management Company', id: '48' },
    { label: 'Risk Management Company', id: '49' },
    { label: 'Strategy Consulting Firm', id: '50' },
    { label: 'Innovation Consulting Firm', id: '51' },
    { label: 'Accounting Firm', id: '52' },
    { label: 'Investment Banking Firm', id: '53' },
    { label: 'Business Development Company', id: '54' },
    { label: 'Supply Chain Management Company', id: '55' },
    { label: 'Customer Service Company', id: '56' },
    { label: 'Operations Company', id: '57' },
    { label: 'Quality Assurance Company', id: '58' },
    { label: 'Recruiting Firm', id: '59' },
    { label: 'Real Estate Agency', id: '60' },
    { label: 'Event Planning Company', id: '61' },
    { label: 'Hospitality Company', id: '62' },
    { label: 'Recreation Company', id: '63' },
    { label: 'Media Company', id: '64' },
    { label: 'Advertising Firm', id: '65' },
    { label: 'Public Relations Firm', id: '66' },
    { label: 'Brand Management Company', id: '67' },
    { label: 'Insurance Agency', id: '68' },
    { label: 'Financial Advisory Firm', id: '69' },
    { label: 'Legal Services Firm', id: '70' },
    { label: 'Regulatory Consulting Firm', id: '71' },
    { label: 'Compensation & Benefits Consulting Firm', id: '72' },
    { label: 'Employee Relations Consulting Firm', id: '73' },
    { label: 'Organizational Development Consulting Firm', id: '74' },
    { label: 'Network Administration Company', id: '75' },
    { label: 'System Administration Company', id: '76' },
    { label: 'Database Administration Company', id: '77' },
    { label: 'Graphic Design Agency', id: '78' },
    { label: 'Interior Design Company', id: '79' },
    { label: 'Industrial Design Company', id: '80' },
    { label: 'Web Design Agency', id: '81' },
    { label: 'Process Engineering Company', id: '82' },
    { label: 'Quality Assurance Agency', id: '83' },
    { label: 'Product Design Company', id: '84' },
    { label: 'Shipping & Receiving Company', id: '85' },
    { label: 'Inventory Management Company', id: '86' },
    { label: 'Transportation Agency', id: '87' },
    { label: 'Warehousing Agency', id: '88' },
    { label: 'Business Planning Company', id: '89' },
    { label: 'Market Analysis Company', id: '90' },
    { label: 'Financial Planning Company', id: '91' },
    { label: 'Competitive Analysis Company', id: '92' },
    { label: 'Product Development Company', id: '93' },
    { label: 'Process Improvement Company', id: '94' },
    { label: 'Research & Development Company', id: '95' },
    { label: 'Idea Generation Company', id: '96' },
    { label: 'Bookkeeping Firm', id: '97' },
    { label: 'Financial Analysis Company', id: '98' },
    { label: 'Insurance Brokerage Company', id: '99' },
    { label: 'Business Coaching Company', id: '100' }
  ]
  export default businessTypes